#!/usr/bin/env python3
"""
Mosferics Price List Generator
Version: 1.0.3
"""

# ── Version — increment this whenever you push an update ──────────────────
VERSION = "1.0.3"

# ── Update URL — replace with your GitHub raw file URL after setup ─────────
UPDATE_URL = "https://raw.githubusercontent.com/alt-ts/mosferics-tools/refs/heads/main/generate_price_list.py"

import os, sys, io, tempfile, datetime, base64, re
from pathlib import Path
 
# ── Embedded white logo ────────────────────────────────────────────────────
LOGO_B64 = "iVBORw0KGgoAAAANSUhEUgAABdwAAAXcCAYAAAA4NUxkAABNkElEQVR4nOzd63LjNrqGUTqV+79l7x+JdmsUHUjxJfABWKsqNZmZbpsHEIQe09LP7+/vBgAAAAAAnPNX7w0AAAAAAIAZCO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABDwd+8NAAC6+P3w///s+Puf/gzrOju+AAD4X5/WV59Yf83N+ruQn9/fs9crAFBEhZu6hdxcKoypG2MLAJhN77WW9VU9vcfEPePjS4I7MLLbBOYm0Nf9jcS5uN6oN25jo7ZRx9W2GVvm4PasP+bm/MJn7j3nVV57OaftVB4H7xgjHwjuwBmVJpDVJ/xK52LbnI8zqp3LqxkrbRlf81jtXFaXHGvObR1XzyHO9Tkzz/GvVB4zK56PPSqfs28518fMOAbeMT42wR04p9IEsvKkXuk83Fv5nHyj6nlsxXi5lvE1l9XPZ1Wpceb81nHl3OE8X2O2+f5R9XEz+/H/pPr5SVv9fH+y2nh4tPT4ENyBb1WcPFad0J2LcVU8d1UYQ+cYW6/NMrac41o84T4nT7jPw9x/vVmO8VGVz0lLq57/R8bDc8uNj797bwAALMhC7LPHY7TcIu0LxtU+v5vxBLAa7znOFay9/lh5fWUcfLbc56MI7sBMVrzJu7mPw7k6Z7lF2gHG1nF+oAOwLvGdb1lzvbfa+sp4OG6Z+fev3hsADMmNBfb73VwzSb+bY3rPcchwHAHWZE3BXsbJcTMfs5n3rZWp519PuAOzWekp98o3p5XOwyuVz88sVn7q3fjKW+aJGwD+Y+U1Be9Zc50z2/rKeMibcv4V3AEgyyKsvSkXaS8YX22sNKYA+GO2OMj3rLnyRn0oy1hoY6r1t+AOzGjUGznjsgirYapF2hPGWXuzjykAXvOaYj3WWtcbbW1lTLQ32hh5ynu4A8A5FmH1OCcAAFCX9TqfDD1GPOEOHDXKpDfzEymjnIPZjXgezlwTo+3vFE9G/GuUY5881tX2eabxBOw383ryk5/tv3PfnuNRbf4+y1vMrGGWcXt2jLY+DlXXVyONh5nX39tWd4x8JLgDwHEVFyOP0ouS+693e8E9wnEYPZZUPMYtjmfV8TXsop9LGQ/zWv3cPu7/nuOx589UnN/3GH1NwXOjjsdtu269L7zXs/L6e9sGnH8FdwCuMtxNcaeqi5Bta3e8fx7+c9tqH5dRF/GVjmmPY1d5fI06psgzBua18rm9et8rz++sY8Sx13qt/+jqY1bh9WOlcWH9/b+GWn8L7sAR1SbcTyrcsJlL1WugwjivvDi7GWlOqHAMKx2rquNrpDHVkmMyN+eXpKrz+ytDBR9eGmGs3VtpvPVcW1UYF5XOddX5eYh5WHAHGEulG90es8Soise98nHt9euoewyxQOus+rGpNr5mmedgD2OdK1Wb398x949phLF1r9oYaxVgV72+Ku9zxfheepz81XsDAC5W5WbAuIyh7/1shRdBRf1ufcfcSOer0vjqfd4AZlJlbv/EvM9VKq1xXrl6+3q9j3wPI5zve5W2tew8LLgDjKPszWRSVQPaaAuybau5vRXPb+/tqXie9qh0TfQ+hwCzqDKvf2LeH0PFdd8zldY0e1y9va3OWe/YPqJKY7Xk9S24A8A4qixqvlF128stzjqpen6OmGEfZuA8ACnmExJGWOtVipffuHL7Rzh/Kxt53F5KcAdW4Cbd12jHv+JPyEdfhN/8bDX3pdr5bqni+Thjtv0Z0crXE5A3wrxu3qtrhHNTfXwfcdX1OsJ5PGqEuW2vCq/xyh1LwR3Ya8abHMCNOW4uvRbd5Rb7ALCoEdZ21g37jXA+6aPkdSS4A4zBAqONise55AJiUj3Pf8WxN7qW107vp3oAZmeO5YgR1lUzj+mR1kUjjJWRtD73ZceZ4A6sYuQb6cjbPpJqx3mkheo3qu5ftXHAOS3GWMVxDDCjyvOt9UMd1c9F1TXwFdL7Wf3c8sfVY7z8dSS4A3u4sTE7Y5x7xsNcrlyMl17oA8Biqq/hrBvOS57j6uNldFeN9yGuI8EdWMmIN9QRt3k0jnFfQyyYGF56nJV/qgYAFmNNX5P1EilDrb8FdwBWVnFhPtRCImS1/X1UcRzOKDHOVrw+AaC6EdZSK68fVt731f1si66fBXcAWhhhEQzM78yCf7kXCgBAhDWEY8D3hgz2gjuwmpHC70jbOqKKx3e4hURQtYXU71ZzjKStsI8JlcYmwMoqz8fuqTxTecyOJvl6wfVaX7XXh4cI7gAAr1mMM+xCHwAWUHmtZg0Bfyx1PQjuwCeVFzDfmnGfOMYYgD9WvB72PDEz9FM1ALCAFdcwIzuyrvp58s9MVh27e8/j8OdbcAeoadUb8MqGX1RMbIXrcYV9PML1CACcYS3x3LvjMmtcf2XV9fer8zvV+RfcgRYqTpqVb26Jbat2vLetzjGvsh1QjWvjHxXnTwCAWfw8/HvFXtCK9fc/pjv/gjvwTnryn24ShRDXxh9Vj8Uqi+FVPiz2mZVf7AHAaCqvV6wnPrPu+mPF9ffjD12m83fvDQAgbsobVshqCxmyfrd1rq/btTL7/s6+fwAwI2t6ZrTK+vtm6v30hDsAAK+s+MQNAMC3po6INLHi+nu6/RXcgdYqLUAq3sjObk+l41tNtXN945z910rHpOq4fFRxvgQA1lN5PbLSGnZ0I5yr322dNfgI5+MQbykDwApWWKTQRvptZX62scbn47ZOtzgGoLSR7pkAKc/mPuvwwgR3gDqu+JBaL0qAKwnwAEArXtvAH9bhhQnuwCupxcyzSV8IXtdKHzoJK3o3t7v2AZiZ+xzQk6fgCxHcAWpE4MQPIHrvAyRV/sHc6m8r8y0vAgCYlfsZxgAVeQq+E8EdeKZF+FklMPXmONdmwcPqRHgA9qq6pnXfaqPq+WdcK75W9tuojQjuAP+o8JT7Khxr+K8VF/yviPAAPHKPXJvzD9fzNHyQ4A7QnwUkwHteAAAAVVmXjMtDL69Zf58guANX+jQhu7llvDvOFY9v6xt1xWOwbRYse1SeI/ymRl9eAEB7rjP4L9cFjK/ya45KrL8PENwB/ugR0Fa8sQuV8JzF/ve8DQ3AvNwbgatZhx9n/f2G4A4wNwsHGMttkeq6Pe/+GFr8w3m3a8r1REtV74euA4D/sv7+l+AOPGq9qK0WhFs+fV1pvwFmJhS2Ner9zfjYZ8Tz69wC8Em1NjG6x/X3Ur/p/lfvDQDYFpp0+X8WMvCeefEavw//wD1jYl7O7Ziqnjf3aJiX6zvvft29zBpccAfuLTHx7dDiOKS+x54FgUUDjMm1e71lFv0AgzE3Mwrrtfk4p9ebfg3uLWWAKvz61nEWAjA/c2Mbj8fY/ArQT+X7nvsDrMHnKrUx7Xu+e8IdAKC2qRafADAo92MAdvGEO8BzV36gh5+St+NYM4vH+cjYvta0T9vAolzHx/T4YLuq9zVjB9Z2PwdUnadmMdVvnHrCHQAAXvPiCuA607+PLwDr8YQ7UIn3KgbYx9M2bU31xA3ABy3muBHuXeZ64J71d1tDr78Fd+AmfcMYajJ84Ypfp00dZ8cXuPHDSgBGMMK9ytoU2MOHqvKW4A5UUy0cJaNwz/2qdlyBLE/cAJCSWP+6FwErsAbnKcEdYDwzPXnjKXfI8wO2692Or/kLmNVK9xFzOZBgDX6t+2Nbft72oalAReUnT4Difh7+4RpeVAGMzT0SSLL+bqP8GtwT7sAV3FwAavE+k9fxmzoA4zFvA1d7nGeswxciuAPbVnPir/TrWJXex9KLg3mIdGMb9dw92+4qc+3IvMXMPMzN71Van73i/PGO8UGa+wZ7eb/3rNLXnuAOwMxGCAPQm8U/aWVf/BDh/DIi4xaoxPo7o2x0F9wB9ik7kQME+dVXAGZi/Q5U5zdQzynZagR3oPJEPsvTyd5OBr4zw/U/OgH+GG8tA9CX+XdOs7wuhL18/tIx5aK74A6w3zeTeKUbpIUqcJYncACopFRgAQh7NcdZf/9Xqej+V+8NAPigzIT5heRNcOTj8MnVi4WZjx1U8LO5zgBo4+fhH9ZR+XyLn7RmDizOE+4AQEWVX7hY3D737rhUPp8A1OfeC/Bf1t//q8xT7oI7wDFlJnCmYDyxCm9FAzCGkd8+EYA/rL87EtxhbVdMtivEw9aRdIVjejXvXw/1zPxEjg9PBUZ1dJ3bao1lXqU6D9IwgpnX36UI7gAAAAAA63qM8QL8CT40FRjBiE8KVL05VT2WVY8XPKp6Dc3m8UPxHHeAulrO0b+bdePKrAegHWvxEwR3YBTVJvh3C30vAjjCePkvx4RnLPoBuLFWWFflNYBxycyswQ8Q3AFqc0PLcSw5yxiqRXwHAIC2rL93ENxhXSN+YGq1Sf3ZMfRUQ23VxtCNcfOHY3GcY1b32gbgOt5eZl2V7/vG5BrMP8L7W4I7rGn1G8MoVrt5GZdUVvF6vF/oW/TXPEcAXG/1+x/Q1u+Lf1+V8P6E4A6Q42YLtGK+ec6CHwDW4H5PD37LnV0Ed2A01RZWV91cr9zPasewtapBzkKt7jGoNF4+Pcle9Ri2VumcAayg9/rKb3qtqer93lh87/fFP1Xt2cbK299K1euxC8EdAGAMexfyFvwAAFSzJ1pXi++VtmUEovu/BHeA86otChiXcVRPhUXjN3OMsVTj3AHQlnU5VRiH51SI79+sv513tm0T3IExiSgkGEe1VFuc9v7V+Jszx6XaMV1NhfED0FqVuc89cB1VxtwzxmFG6/h+9nutft4rX5PNCO7AqGaexGfet09aL04qHusVF2gr7vMnqRcVqx/bitc4wOyqzL2r3wOpwTjMxvKrj6fzRYTgDqRUWVjDDFZa6K20r704xu25JwLU4B64hiq/mfjKyuNwpH1Pbqu3l+mjzDwguMN6TPq1tbpBlLkRFeBY9FN1Puo5Jq5anFc91gDMqdL6yj2QCozDuq6M4877ogR3AKj1opC+esf2kb8+AEBP1vTzS59j62MuIbgDI5ttQTXb/oym2vGf/dcQK+5brzEw0odAjWalfQWoptLaarX738oqv73MSuPwin1Nnlfr7+v02tdS173gDgB/lLpJ/2vGxdmM+/QtxwIA2nHfpYLZx2H1/eu1fauF96UJ7sDoKgZSxlZxTM20MKu4L72ehOp5LH43i/6rVJxDAHqpOCe6962h8pPu2zbnOLxybZk6lxWOuzX4AgR3WItJnRFUGKcVF+cVjstZFfeh4rlureJ5OavXCxnjCeC/Ks6NM977eK7i+LsxDvdJnsNK42HG8+/tZP4luAMzKDe5fqHHPsxw3K5U8fiMuijzFMdzlcaY8wPAaqxPqGCGcTjCk+1VzfRbpzPsQ4zgDiTMfhO8muNXV8VzM9qCrOq2Vvk14wrbcDPDgr/n9lc6lwDsN/J9j32qrPveGXEcXr3uuuqcVR8LI+o5fkuez797bwBAyM825iKF5363OjfOqmPrtk1VjtOjisds22oer4pjrPr4etT7+I1ynAB6qXivuzfafY853V8jlcdii2v56v2/ff1K89Io5/9e7+NX9jh5wh0APit7I9/6L3LIqDrGRn/iHYA6qt7rWMcIT7rfVF1/zRDbe32vI6qe/3u9t7Hqudu2zRPusJLek2EL1Z+cYWyPN/RKY63C0xCVjsczpRdk/7rfxmrH83F7eh/PSsen97GAlipdey24vvMqPlV6z5Pua6g+Dm8qrL9aHqNe113V8VDh/D+qcowqHIu3BHcAmEvrhVmVRdc75RdkA2r9Q54RxhkA86j09oZw03L9teLaq/oDfNbfAxHcAeA71RdkN6mF2Qj7+mjkF8pVn7R55tk2nj32I+z3to09xgB6GmEd5Wn3+Y203no00/qr0jU2ypiY6fwfVWm8vCS4wxpGmTgTRli83xviZsFLo423kbb1rFmurVEW/Y9G296jZhlfAD2Nso7ytPv8Rl1vPRpt+ytfVyOOiZG29RuVx8t/+NBUgH4q3DAqbMPoRvrwpdn9bPOejxn3aUSzji+AXkaZU32I+Brc59sZ5TiPsp0U4wl34KyKN6BRnpZhLiM+BTGTinNRWuUPVV3BCmMMgPe8zcwavJ68xqjXjdd5/Yw6ZgR3AAizQG9r2EXYSRb+7aw6xgBaGXHtJLzPz4MOWTNcK9bfbQ09ZgR3mJ+bQU1D3zz4yAL9eq6hf4wYKUZinAG04X5GZULr92ZcSxkP15pizAjuwBmVJ0KL9vHN8gFVFmQ5M4yHKxhjecYacLXKc3avNdiI97P7bXXvmN+IY7Sn2a+Jx/0zLs6Zarz40FQAKptp0eJDmL7n2O3jGJ1nrAH0N+o8PNO6lfdGHaMt/GzWUxw33XjxhDsws6pPuU93M+GQZ+e/4jjtzXXyHePrO8YbQC1V1/GfeG/3dXgLyX8Y638YE8dMPXYEd5ibSR7G4NdTJ19wdWZ8/ZfxBvBalTly5PuX8L6WFd9axNh+T3x/bplxI7gDs6v2dEzFG0y1Y7SylZ5OrngtzG6l8fXIeAOqsf7az7FiNDOuuaylvrfiD2Rulh03P7+/K51nWNazJyz2XPwzTY5XfPjT0Ql0pOO553idvYGMdDwqGukG7lyPZ6Tx9cxKY+5+vm553p6tKVY67q08+0DG0a/PUbQaz9XOZ/XruPfx2rs+vvo4vnp9d/X6/eZ+Pqo+ZqrqPZY/cV7bqz4mPjFm7gjuADCHCjd0i6x5VRhfrxh3AMDIeq2zrKFqq7b+Nl4OENwBYE2fFgAWVJxhfAEAAEvyHu4AsCbBkysZXwAAwJL+6r0BAAAAAAAwA8EdAAAAAAACBHcAAAAAAAgQ3AEAAAAAIEBwBwAAAACAAMEdAAAAAAACBHcAAAAAAAgQ3AEAAAAAIEBwBwAAAACAAMEdAAAAAAACBHcAAAAAAAgQ3AEAAAAAIODv3hsAAAAAwNB+7/79p9tWABQguAMwIwt+AABo4/fNf7cWB5YjuAMwi8eF/uP/brEPAIzu1XqnCuut9Xwak7+bcQEsRnCHNfRcmFtccZWj4/rxz68+Nqu8YF/9PADAXlXu3e940GEtI4xJgOYEd+Bqfp2QpOSifuUXhJVeHK18HgBgr0r3bgDgDcEd5ldpcS6sccZVY3m1cVlpTrjnNxAAAObkbWWApfzVewOAJf3e/QN7tBgrxmMtzgcAwBzEdmApgjvQm6jGJ8bIupx7AIC69oR0sR1YjuAOVCCq8YzfgmDbjAEAGO1eKLCu5d35NhaAJXkPd5jbSItz7+vHWZ/Gz0jXA//L/DC31T5HAWjH/NKeY70m5x04a6rXfII78OjbCS4RM6eaYGlm75i5/3Pi+2dnr8X0MTY/zOn34d+dYyBlpvnlZ9t3Xx15HwHg/l439D1NcIe5tVycp54uHv0FERlXj1tj7L1Wc8LeOer+7+z52ozBD76AK5hbAGAcU963vYc7ANDDz8N/spYpF9YAAMBu074mENyBVkQ1koynuTifa5l2YQ105cPWAWAM09+zBXegJVENeMX8sIapF9ZAN+YWABjDEvdswR1oTVTjLGNoXnvP7RKLtAk5b8AVzC0AMIa99+zhX/P70FSgIh+cCjAPMQy4grmFe4/jwWuJ+azwGnGFfazo0/1klnPSez+P3LeHvxYEd2BlR1+o9Zzwb9t6Zhte7e9oN7Lhb7689bPViyh7tqfKmDxz7O73ITHn3H+dI3/+yBhIH/dvj9/o94fE979Jbsf91z7ydVu/oExdd1c7e64qXR/fbMtI6z5e23sev133XrVerrIOf7YdiW246us+fu0j97yz68le83OrfWy9xkt+7299u81Xju+j33fv9z57n7xqPXfl3yt13/75/a32mhYIqxqKRvrp6iutjtu3L5CP7GOpm9PWf3zMrOqccK/CNo70Iu3mqkXdFT/oS7oqFJxR/UXYld8/sQ3pUHb063wy03jZ8/2rrZlavoDtfT+8V+HeWMHV9+cr5rZK69or7h097gfvvnZyjqg8P/eam1PHd4a18pX78O28UW38r3rPFtxhARUX5y23aeQJvuVNttLNaZn3deuk4pzwzEhPqH5S/YcDR1R8n/2eLxb3qnJ/aPX9z2zD0X1r9YRd9TH9ToUX7Z++116jX7tnjHL/vkLLe/QV82uFc1dp3k593cevPeJaruU978j3eTTisb0Z5eGPe99crxXPUa/gXOJe6ENTgYpSP0ltPcFX+H5+igrHXX3dXPn1K17zFbfpXo/tq35MeK3HeqK3K/f5zNde7TzQ/vozxsbVYi038/h4t28j73erbe89Piq+lhl53EQI7kBrLSbemW92V33vSjfEEj+RpqsZX1ynF+K9F/avVI/Zo87RPFfxBWbq+844D575nq6f9bS+PxtjY+oxX/aan3vc80Z+7d7r3lbhIbyRv89ZZVqC4A6QN8rN6F6ZG9O/9n4QzIjHmhp6jR9jdm3O/3m/D/85sx4v2mcP/dRnfccIZo7899931O+1whxSOe4v/VYyN4I70NIKN76b1j9pXunYMrcK73N6tbO/jeJ6/1+jjQfn77zEMRxl3Hhy7R+tz9dPh+8JjKX6vPmNM7/x8bOdmztTx/PM1/nZzu/H2W24SsvPyHv8XmeOa+J8dPF37w0AlrH3pjPcRPrG79b/k+33qHrMf7Z9+9bqODOHb19ApL9my3Hb84Mhb9/76NftfU1f/eFh5q02Wh7jK6+zauMleX0c2bfH+WTvOuHZ16Ceb+fVih/mTS2zz897fzO45fdu9WG2j458rz3H7cwHk1YcG++256rXAK/+v2/D/TAEd6CF1rF9zwTe6ifvFW6021ZjG75xJLrf/jzjqvR+zEfG0rcvKo7OD1dtf+Lvffr73y6s015txzdP2zwa9f4wm+Qx/TRuz1xnI8W/b66PK+fCnyf/XmF+4XtX/DD83Z8f6frjO2fXQSOE1W/mzR4PalW857UaHyOMjfu/U2m/hr9nC+7AlXreWK+aoCsuGF4Z/iYFnZy5do6+oF8pulaZP6+8P2xbjX1c0dXn9aqvW+nF7TMto9WVVplnV5A4l1XuR+S1fICrl09PKVec76rcE2YfH4kHZ0b+oNxSBHdg22pMeBUXBq+0epHsV6X/cfSn7fd/j+NaH7cWT20f+T4tn469Sb44Mu77q/oibAQtnnKtpkqEuDf6PNjj61cx4gfV9XrbSU+8z+WK6/vI/Fzlid9Pf+bbNUqr+fPb31ru8VtOe8dHlbFx9Gv13q/h79s+NBWoYOiJlMt5ETSX34d/Wn3PPa58sQYAsxr9A73dq8fm/B3jeGU5njwluAM9/Wxj36Aqbfvox/IKI7/w6+mKF81nA3uL8e36Icl4amOm41xlX6psB2P65rMsqjD2x7TKeeu5nzMc4xn24ZWZ921o3lIG4JwKbx0w6002cVyH/1W0jnqP65sW56/XB3UyN+f9Oub1a/j8G84a7bMUYI8qb43V2ij7MsL95YqxMcr5WZYn3IGeRv/1U8ZgjDEC43RNzjtHXDlevHCntZ5v9wZHecI8Y6QP/4ZTBHegAuGde1e+pQnj8DZJ3zHWAejBPZvZGeP1VFnzGhv8h+AOVCIUHTfbzf3I+f8myBpfY0iO61XPeesPpuW/HHuAc2Zb50IVrq32rAsX4z3cgUe3m2/ifca+vamM9P53e/dxpH3q5cwHah75u7c/63zUNMt5qXTNP7s+qmxbVWdfFDm+1xnh2HpRTU8jXCMAPaTvzz6jhJcEd2Dbni/ME4v1Z1+jUqBueXP04ifn3Xi14Bnf/Tlsdd1cNW6Oft1P8979/3d2mx//vjkqOw7MRdep8sMs55iKKlwbsLIq9yj+uPJ+bS3AS4I70FqvnwK7GdbW44OzLIjrc47aWTXAuzdwhPECAMBHgjvQw96nkXu+rQ317BkL37y9TOp94GcLlFfszzfXo+jex+xvveTewBHGCwAAu/nQVGBmXiDP40j0O/phqkc+WHKVMXVVZP3Zjp+fbXPcX/3ZFjF8tmPvg2Q5yngBAOAQwR3oaU8s8kJ3fled42+i7pltmWWstnqiWXTPaBHeZzn2s+wH7RgzAMAZ3z5wxOC8pQwwIy+QuUl+ZoBxldfiLYBGkPyQ6qs/AHbU458+Lp+Og/libGfP397xkfwgZADgtVHXsAxKcAd6S3+I6jdfy/vEz+2bqHv7e4//26fvM4PWUbvXByk/ejzfo57PFuF9tGPT475w9XmglqPj5dmfrzIXAsBsRlu7MgHBHZjJkReqyZuuF8n1OUe19T4/j/PBDIvyK5/AHjG675Xer95jm2vNeh0AwCzcq+nCe7gDs9gbNK54/7Sr38Jhdanz9e2Hqa70dHtPPY/hitfaz8M/XHMcVhxbo9s754+yloCRuS4YjTVVWz4TbkxLXCeCOwCrWeIGz/9zvvdZ/Titvv/0ZwxCf65DXtn7EA41OXc0J7gDvbW8+VlEc5N8OtG4ynEs+/K0O3zmGoGMvddSy9cKV32v3k/hio0AjQnuAFR35YsE4WQ83sLpeqtdF6vt7xme8ANmNevcNut+3bTYvyNvXUp7FX94B4I70JWbHtvWf3F65qne3tvOPhbi9NBzPF3xvV0f13J8WVGV+3OV6y+9HVX262qr7CcwEMEdqK5y0PSkXzstjnPlsUY7run1zBqnk9tQYX9m5viysp7Rfda1/Kz79U7v34D0OmIMK14bdPJ37w0AltP7ib/EYshNuo/U+Xv1tb/9exbY7V193Ft8/Ztvv8/ta6S30/x2zmzHb7b9SUjOD44vHJO4fz5+ndnMvG+fpMbH49eivp/t2DlLr6PffW+vFRflCXegpRkWLj7k9Ro993WGcclnva+n3+35UzVnx1/ySZ2Vr4XEvlc8fme2qeL+zMTxhT++uUe7hnjnzPro6N/rvcaknz3jzFy1KE+4w9z2Tu4tn+Y84optOrOvZ8NFtf0ZUcUnV6560nhVR59QucqzbagQBF59vcf//ci2VjjeNz2vp2+/d4/jd+Q6+Wa/Ko2J1vYc25HGCn/sOW+j39MrjLGzn4vzzVOqj3//cRsqHZdv4tyzY1phn0bw7ppOHMMWc8UVr/dmHD9n5xDq2fPaP9kHogR3mNs3L8irODpZXhEfksek1ORf1Le/Cnj7u3v/7FVm+eHHDPvwytmYf+X7g+457iu9gDiy/Z+O3Zm5pbJZ92skjumY9py3We7pPfQ6dr8v/n0Gs+1PD1ccw1bj3Fx0TJWHd3jvinVsqXu34A5U1GqSnOFGXOaGEvLtAqnKuSx1k+epb55+4Y+K49t1B1wRWMwt33Ps6rDuucbo43vvb3ONup+i+7rKjFvv4Q5Uc2ZyLDGxctrPVutcHt2e0Rd3o28/tfX64OPWc0qreaz1fHn199vztVsdV9g298Qeqq0D01ruX6u3O+lptvsgOc5TfVOfI8EdqCK1eJl60qapxzG5UnRfQaUXTHu3o+f2Vjpe3xp9+98RofMEnPE4hnOZ/Rq8+vvNFPX3qLId1NL7/tr7+49g2uMjuAMVpCfZlgtMN9Hr9Hrx8+77OtfzGW0RPkMUuGL7q/zQYsZ7wrN92vO++We+XxWtf5Bx1ferdEyvNsJ8xX4tfqum9zrgiq+56ri9cg696rhWPle9tm2G6+Ls96swLq5c6135tcr4+f31EB4soNqF3mpCvWq/n23/VW9n8O7rTnljeqHFGD56PEc+N9W3vdfbg1QcZ59cuc2j/Cr6N9vZ6sPTRh7Ln7btynnk1dfuOT+1+iD1mY9ry3tPr7nlatXW9K9ceezOHoNvr789f/9bveeXxD5d8bXPno+R5oFe83PP+8Kz7937eH+r9bxQ4ThVnQvL3LsFd1hDzwu9woTXauK+4oZU4UZbSasXJHuMfm56h5d3qhzbSuNtrxEXqt9sc3Ibr/7+1V7M7rF3267at6rz05nrq8KY6Rk3em5D7zmmhUov6qve786u5Y98nTOu2K933yO1P1dc28nzceS49rj+b9v38/DvPbah5ffu8T2faXHdnVHlOLVU7fOZDhPcgdVUX2yR83iunU+Sqi8Cq28fAFRTIbjzh/MBDOvv3hsA0FjPpwbow3nmCtXHVfXtAwAAmJLgDqxIiFqD8wwAAAA09VfvDQAAAAAAgBkI7gAAAAAAECC4AwAAAABAgOAOAAAAAAABgjsAAAAAAAQI7gAAAAAAECC4AwAAAABAgOAOAAAAAAABgjsAAAAAAAQI7gAAAAAAECC4AwAAAABAgOAOAAAAAAABgjsAAAAAAAQI7gAAAMDqfnpvAP/j0/lwvoCyBHcAAACA9xFX4G3v1TF3LoDS/u69AQAAAABFiLm1OB/AcDzhDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7AAAAAAAECO4AAAAAABAguAMAAAAAQIDgDgAAAAAAAYI7wP+1Y8cCAAAAAIP8rSexszACAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAICBcAcAAAAAgIFwBwAAAACAgXAHAAAAAIBBWeX8iJVtlroAAAAASUVORK5CYII="
 
LIST_COLUMNS = ['Bar & Club', 'Bar & Casual Food', 'Cocktail Bar', 'Restaurant', 'Personalised']
 
# ── Auto-update ────────────────────────────────────────────────────────────
def check_for_update(silent=False):
    """
    Fetches the latest script from GitHub, compares version numbers,
    and if newer: saves the update and relaunches the program.
    Returns True if an update was applied (caller should exit).
    """
    import urllib.request, urllib.error
 
    # Don't update if running as a frozen PyInstaller exe during development
    # (comment out this block once you're happy with updates working)
 
    try:
        req = urllib.request.Request(
            UPDATE_URL,
            headers={'Cache-Control': 'no-cache', 'User-Agent': 'MosfericsUpdater/1.0'}
        )
        with urllib.request.urlopen(req, timeout=5) as resp:
            remote_src = resp.read().decode('utf-8')
    except Exception:
        # No internet or URL not set up yet — silently continue
        return False
 
    # Extract remote version
    match = re.search(r'^VERSION\s*=\s*["\']([^"\']+)["\']', remote_src, re.MULTILINE)
    if not match:
        return False
 
    remote_ver = match.group(1)
 
    def ver_tuple(v):
        try:
            return tuple(int(x) for x in v.split('.'))
        except ValueError:
            return (0,)
 
    if ver_tuple(remote_ver) <= ver_tuple(VERSION):
        return False  # Already up to date
 
    # Newer version available — ask user
    import tkinter as tk
    from tkinter import messagebox
    root = tk.Tk()
    root.withdraw()
 
    if not messagebox.askyesno(
        'Update Available',
        f'A new version is available (v{remote_ver}).\n\n'
        f'You are currently on v{VERSION}.\n\n'
        'Update now? The app will restart automatically.'
    ):
        root.destroy()
        return False
 
    root.destroy()
 
    # Save the new script alongside the current executable/script
    if getattr(sys, 'frozen', False):
        # Running as PyInstaller executable
        current_path = Path(sys.executable)
    else:
        # Running as .py script
        current_path = Path(__file__)
 
    # Write to a temp file first, then atomically replace the current script
    tmp_update = current_path.with_suffix('.tmp_update.py')
    try:
        tmp_update.write_text(remote_src, encoding='utf-8')
    except Exception as e:
        import tkinter as tk
        from tkinter import messagebox
        r = tk.Tk(); r.withdraw()
        messagebox.showerror('Update failed', f'Could not save update:\n{e}')
        r.destroy()
        return False
 
    # Replace current script with updated version
    try:
        # On Windows, can't replace a running file directly — rename current first
        import subprocess
        backup = current_path.with_suffix('.backup.py')
        if backup.exists():
            backup.unlink()
        current_path.rename(backup)
        tmp_update.rename(current_path)
        # Clean up backup
        try: backup.unlink()
        except: pass
    except Exception as e:
        # Rename failed — try direct overwrite
        try:
            current_path.write_text(remote_src, encoding='utf-8')
            tmp_update.unlink(missing_ok=True)
        except Exception:
            pass
 
    # Relaunch the updated script
    import subprocess
    try:
        subprocess.Popen([sys.executable, str(current_path)])
        return True
    except Exception:
        return False
 
# ── Logo loader ────────────────────────────────────────────────────────────
def get_logo_reader():
    from reportlab.lib.utils import ImageReader
    data = base64.b64decode(LOGO_B64)
    return ImageReader(io.BytesIO(data))
 
# ── Data loader ────────────────────────────────────────────────────────────
def load_products(excel_path, list_name):
    import openpyxl
    wb = openpyxl.load_workbook(excel_path, data_only=True)
    ws = wb.active
    headers = [cell.value for cell in next(ws.iter_rows())]
 
    if list_name not in headers:
        raise ValueError(f"Column '{list_name}' not found in the Excel file.")
 
    products, seen = [], set()
    for row in ws.iter_rows(min_row=2, values_only=True):
        d = dict(zip(headers, row))
        if not d.get(list_name):
            continue
        cat = str(d.get('Price File Category') or '').strip()
        if not cat or cat.lower() == 'none':
            continue
        title = str(d.get('Title') or '').strip()
        sku   = str(d.get('Variant SKU') or '').strip()
        price = d.get('Variant Price')
        if not title or not sku or price is None:
            continue
        if sku in seen:
            continue
        seen.add(sku)
        try:
            price = float(price)
        except (TypeError, ValueError):
            continue
        cat = cat.replace('Dipsoables', 'Disposables')
        products.append({'category': cat, 'title': title, 'sku': sku, 'price': price})
 
    if not products:
        raise ValueError(
            f"No products found for '{list_name}'.\n\n"
            "Check that TRUE is in the correct column for at least one product "
            "and that 'Price File Category' is filled in for those products."
        )
 
    grouped = {}
    for p in products:
        grouped.setdefault(p['category'], []).append(p)
    for cat in grouped:
        grouped[cat].sort(key=lambda x: x['title'])
    return dict(sorted(grouped.items()))
 
# ── PDF generator ──────────────────────────────────────────────────────────
def generate_pdf(grouped_products, list_name, output_path):
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas
    from pypdf import PdfWriter, PdfReader
 
    W, H = A4
    ml, mr = 18*mm, 18*mm
    F, FB, FS = 'Helvetica', 'Helvetica-Bold', 7.0
    LH, RH, CH = 3.8*mm, 8*mm, 7.5*mm
    HDR = 28*mm + 2.5*mm + 8*mm
    FTR, NH = 14*mm, 9*mm
    NB = NH + 10*mm
 
    def hx(h): return colors.HexColor(h)
 
    logo_img = get_logo_reader()
 
    sku_w, price_w, gap = 26*mm, 28*mm, 2*mm
    name_w  = W - ml - mr - sku_w - gap - price_w - gap
    sku_x   = ml
    name_x  = sku_x + sku_w + gap
    price_x = name_x + name_w + gap
 
    def wrap(ref_c, text, max_w):
        words = str(text).split()
        lines, cur = [], ''
        for w in words:
            test = (cur + ' ' + w).strip()
            if ref_c.stringWidth(test, F, FS) <= max_w:
                cur = test
            else:
                if cur: lines.append(cur)
                cur = w
        if cur: lines.append(cur)
        return lines or [str(text)]
 
    def row_h(lines): return max(RH, len(lines) * LH + 4*mm)
 
    tmp0 = tempfile.mktemp(suffix='.pdf')
    ref  = canvas.Canvas(tmp0, pagesize=A4)
    ref.setFont(F, FS)
 
    all_items = []
    for cat, prods in grouped_products.items():
        all_items.append(('cat', cat))
        for p in prods:
            lines = wrap(ref, p['title'], name_w)
            all_items.append(('row', p['sku'], p['title'], p['price'], lines, row_h(lines)))
 
    avail_n = H - HDR - FTR - 4*mm
    avail_l = H - HDR - FTR - NB - 4*mm
    pages, cur_pg, used = [], [], 0.0
    for it in all_items:
        h = CH if it[0]=='cat' else it[5]
        if used + h > avail_n and cur_pg:
            pages.append(cur_pg); cur_pg=[]; used=0.0
        cur_pg.append(it); used += h
    if cur_pg: pages.append(cur_pg)
    total = len(pages)
 
    last_used = sum(CH if i[0]=='cat' else i[5] for i in pages[-1])
    if last_used > avail_l:
        overflow = []
        while pages[-1] and sum(CH if i[0]=='cat' else i[5] for i in pages[-1]) > avail_l:
            overflow.insert(0, pages[-1].pop())
        if overflow: pages.append(overflow); total = len(pages)
 
    page_files, row_idx = [], 0
 
    for pg_num, pg_items in enumerate(pages, 1):
        is_last = (pg_num == total)
        tmp = tempfile.mktemp(suffix='.pdf')
        page_files.append(tmp)
        c = canvas.Canvas(tmp, pagesize=A4)
 
        c.setFillColor(hx('#f5f5f5'))
        c.rect(0, 0, W, H, fill=1, stroke=0)
 
        c.setFillColor(hx('#1a1a1a'))
        c.rect(0, H-28*mm, W, 28*mm, fill=1, stroke=0)
        c.setFillColor(hx('#e8327a'))
        c.rect(0, H-2.5*mm, W, 2.5*mm, fill=1, stroke=0)
        c.setFillColor(hx('#e8327a'))
        c.rect(0, H-28*mm-2.5*mm, W, 2.5*mm, fill=1, stroke=0)
 
        c.drawImage(logo_img, ml, H-28*mm+5*mm, width=17*mm, height=17*mm, mask='auto')
 
        c.setFillColor(hx('#ffffff'))
        c.setFont(FB, 13)
        c.drawString(ml+22*mm, H-28*mm+17*mm,
                     f'MOSFERICS — {list_name.upper()} PRICE LIST')
        c.setFillColor(hx('#888888'))
        c.setFont(F, 8)
        c.drawString(ml+22*mm, H-28*mm+10*mm,
            f'Trade Price List  |  2025/26  |  All prices ex. VAT  |  Page {pg_num} of {total}')
        today = datetime.date.today().strftime('%d %B %Y')
        c.setFillColor(hx('#888888'))
        c.setFont(F, 7)
        c.drawRightString(W-mr, H-28*mm+17*mm, f'Generated {today}')
        c.setFillColor(hx('#e8327a'))
        c.setFont(FB, 7)
        c.drawRightString(W-mr, H-28*mm+10.5*mm, 'Prices subject to change without notice')
 
        col_y = H-28*mm-2.5*mm-8*mm
        c.setFillColor(hx('#2a2a2a'))
        c.rect(0, col_y, W, 8*mm, fill=1, stroke=0)
        c.setFillColor(hx('#888888'))
        c.setFont(FB, 6.5)
        c.drawString(sku_x+2, col_y+2.8*mm, 'SKU')
        c.drawString(name_x, col_y+2.8*mm, 'PRODUCT DESCRIPTION')
        c.drawCentredString(price_x+price_w/2, col_y+2.8*mm, 'PRICE (EX. VAT)')
 
        cur_y = col_y
 
        for it in pg_items:
            if it[0] == 'cat':
                cur_y -= CH
                c.setFillColor(hx('#333333'))
                c.rect(0, cur_y, W, CH, fill=1, stroke=0)
                c.setFillColor(hx('#e8327a'))
                c.rect(ml, cur_y, 3, CH, fill=1, stroke=0)
                c.setFillColor(hx('#ffffff'))
                c.setFont(FB, 8)
                c.drawString(ml+7, cur_y+2.5*mm, it[1].upper())
            else:
                _, sku, title, price, lines, rh = it
                cur_y -= rh
                c.setFillColor(hx('#ffffff' if row_idx%2==0 else '#f7f7f7'))
                c.rect(0, cur_y, W, rh, fill=1, stroke=0)
                mid = cur_y + rh/2 - 1.5
 
                c.setFillColor(hx('#e8327a'))
                c.setFont(FB, 6.5)
                c.drawString(sku_x+2, mid, sku)
 
                c.setFillColor(hx('#1a1a1a'))
                c.setFont(F, FS)
                bh = len(lines)*LH
                ty = cur_y + (rh+bh)/2 - LH + 0.5*mm
                for i, line in enumerate(lines):
                    c.drawString(name_x, ty - i*LH, line)
 
                c.setFillColor(hx('#1a1a1a'))
                c.setFont(FB, 7.5)
                c.drawCentredString(price_x+price_w/2, mid, f'£{price:.2f}')
 
                c.setStrokeColor(hx('#dddddd'))
                c.setLineWidth(0.3)
                c.line(0, cur_y, W, cur_y)
                row_idx += 1
 
        c.setStrokeColor(hx('#dddddd'))
        c.setLineWidth(0.5)
        c.line(0, cur_y, W, cur_y)
 
        if is_last:
            ny = cur_y - 5*mm
            c.setFillColor(hx('#f2f2f2'))
            c.roundRect(ml, ny-NH, W-ml-mr, NH, 2, fill=1, stroke=0)
            c.setFillColor(hx('#e8327a'))
            c.roundRect(ml, ny-NH, 3, NH, 1.5, fill=1, stroke=0)
            c.setFillColor(hx('#1a1a1a'))
            c.setFont(FB, 6.5)
            c.drawString(ml+6, ny-3.5*mm, 'PRICING NOTE')
            c.setFillColor(hx('#444444'))
            c.setFont(F, 6.5)
            c.drawString(ml+6, ny-7*mm,
                'All prices are per unit/pack as listed, exclusive of VAT. '
                'Prices are subject to change — contact your account manager before ordering.')
 
        c.setFillColor(hx('#1a1a1a'))
        c.rect(0, 0, W, FTR, fill=1, stroke=0)
        c.setFillColor(hx('#e8327a'))
        c.rect(0, FTR-0.6*mm, W, 0.6*mm, fill=1, stroke=0)
        c.setFillColor(hx('#888888'))
        c.setFont(F, 7)
        c.drawString(ml, 5.5*mm,
            'sales@mosferics.com   |   +44 7581 180675   |   www.shop.mosferics.com')
        c.setFillColor(hx('#444444'))
        c.drawRightString(W-mr, 5.5*mm,
            'Mosferics Bar & Restaurant Equipment  |  Trade Only  |  Prices Ex. VAT')
 
        c.save()
 
    writer = PdfWriter()
    for path in page_files:
        for page in PdfReader(path).pages:
            writer.add_page(page)
        try: os.unlink(path)
        except: pass
    try: os.unlink(tmp0)
    except: pass
 
    with open(output_path, 'wb') as f:
        writer.write(f)
 
# ── GUI ────────────────────────────────────────────────────────────────────
def main():
    # Check tkinter is available — Homebrew Python on Mac often lacks it
    try:
        import tkinter as tk
        from tkinter import filedialog, messagebox, ttk
    except ImportError:
        import subprocess, sys
        # Try to show an OS-level error dialog
        msg = (
            "Mosferics Price List Generator could not start.\n\n"
            "The required 'tkinter' module is missing from your Python installation.\n\n"
            "Fix: open Terminal and run:\n"
            "  conda install tk\n\n"
            "Or reinstall using your original Python (miniconda/anaconda)."
        )
        if sys.platform == 'darwin':
            subprocess.run(['osascript', '-e',
                f'display dialog "{msg}" buttons {{"OK"}} default button "OK" '
                f'with title "Mosferics — Missing Dependency"'])
        else:
            print(msg)
        sys.exit(1)
 
    # Check for updates first — 5 second timeout so it never hangs
    if check_for_update():
        sys.exit(0)
 
    root = tk.Tk()
    root.withdraw()
 
    excel_path = filedialog.askopenfilename(
        title='Select Shopify product export',
        filetypes=[('Excel files', '*.xlsx *.xls'), ('All files', '*.*')]
    )
    if not excel_path:
        return
 
    win = tk.Toplevel()
    win.title(f'Mosferics Price List Generator  v{VERSION}')
    win.resizable(False, False)
    win.configure(bg='#1a1a1a')
    win.grab_set()
 
    style = ttk.Style(win)
    style.theme_use('default')
    style.configure('Pink.TButton',
        background='#e8327a', foreground='white',
        font=('Helvetica', 10, 'bold'), padding=(14, 6),
        relief='flat', borderwidth=0)
    style.map('Pink.TButton',
        background=[('active', '#c5205c'), ('pressed', '#a01548')],
        foreground=[('active', 'white'), ('pressed', 'white')])
    style.configure('Grey.TButton',
        background='#444444', foreground='white',
        font=('Helvetica', 10), padding=(14, 6),
        relief='flat', borderwidth=0)
    style.map('Grey.TButton',
        background=[('active', '#555555'), ('pressed', '#333333')],
        foreground=[('active', 'white'), ('pressed', 'white')])
    style.configure('Dark.TRadiobutton',
        background='#1a1a1a', foreground='white',
        font=('Helvetica', 10))
    style.map('Dark.TRadiobutton',
        background=[('active', '#1a1a1a')],
        foreground=[('active', 'white')])
 
    tk.Label(win,
        text='Which price list would you like to generate?',
        font=('Helvetica', 11, 'bold'), fg='white', bg='#1a1a1a',
        wraplength=300, pady=14).pack(padx=20)
 
    selected = tk.StringVar(value=LIST_COLUMNS[0])
    for col in LIST_COLUMNS:
        ttk.Radiobutton(win, text=col, variable=selected,
                        value=col, style='Dark.TRadiobutton').pack(anchor='w', padx=36, pady=2)
 
    confirmed = {'go': False}
 
    def on_generate():
        confirmed['go'] = True
        win.destroy()
 
    btn_frame = tk.Frame(win, bg='#1a1a1a')
    btn_frame.pack(pady=18)
    ttk.Button(btn_frame, text='Generate PDF',
               command=on_generate, style='Pink.TButton').pack(side='left', padx=8)
    ttk.Button(btn_frame, text='Cancel',
               command=win.destroy, style='Grey.TButton').pack(side='left', padx=8)
 
    win.update_idletasks()
    w, h = 360, 280
    x = (win.winfo_screenwidth() - w) // 2
    y = (win.winfo_screenheight() - h) // 2
    win.geometry(f'{w}x{h}+{x}+{y}')
 
    win.wait_window()
    if not confirmed['go']:
        return
 
    list_name = selected.get()
 
    try:
        grouped = load_products(excel_path, list_name)
    except Exception as e:
        messagebox.showerror('Error reading file', str(e))
        return
 
    total     = sum(len(v) for v in grouped.values())
    cat_lines = '\n'.join(f'  \u2022 {k}  ({len(v)} products)' for k, v in grouped.items())
 
    if not messagebox.askyesno('Ready to generate',
        f'Found {total} products in {len(grouped)} categories for "{list_name}":\n\n'
        f'{cat_lines}\n\nGenerate PDF now?'):
        return
 
    # Incrementing filename
    safe      = list_name.replace(' ', '_').replace('&', 'and')
    downloads = Path.home() / 'Downloads'
    downloads.mkdir(exist_ok=True)
    base = downloads / f'Mosferics_{safe}_Price_List.pdf'
    if base.exists():
        counter = 1
        while True:
            candidate = downloads / f'Mosferics_{safe}_Price_List ({counter}).pdf'
            if not candidate.exists():
                base = candidate
                break
            counter += 1
    out = str(base)
 
    try:
        generate_pdf(grouped, list_name, out)
    except Exception as e:
        messagebox.showerror('Error generating PDF', str(e))
        return
 
    messagebox.showinfo('Done!', f'Saved to:\n{out}')
 
    import subprocess, platform
    try:
        if platform.system() == 'Darwin':
            subprocess.run(['open', out])
        elif platform.system() == 'Windows':
            os.startfile(out)
        else:
            subprocess.run(['xdg-open', out])
    except Exception:
        pass
 
if __name__ == '__main__':
    main()
